#!/usr/bin/env python
import matplotlib.pyplot as plt
import seaborn as sns
import os
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform

import numpy as np
import utils

apps = utils.apps

ORDER = 'sm_util'

fig = plt.figure(figsize=(utils.TEXT_WIDTH, 2.65))
axs = fig.subplots(len(apps)//4, 5, sharex='col')

# plt.xticks(fontsize=6)
# plt.yticks(fontsize=6)

for i, app in enumerate(apps):
    batch = utils.get_large_batch_size('a100', app)
    raw_file = utils.get_ncu_raw_file('a100', app, batch)
    r, c = i // 4, i % 4

    prettyname = utils.app_pretty_names[app]
    print(f'Processing {prettyname}...')

    _, data = utils.read_ncu_raw_file_numpy(
        raw_file,
        [
            'gpu__time_duration.sum',
            'sm__throughput.avg.pct_of_peak_sustained_elapsed',
            'gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed',
            'sm__pipe_tensor_cycles_active.avg.pct_of_peak_sustained_elapsed'
        ])

    chrono_data = data.copy()

    if ORDER == 'sm_util':
        # Sort data by sm utilization
        data = data[data[:, 1].argsort()]

    times = data[:, 0]
    sm_util = data[:, 1]
    dram_util = data[:, 2]
    tensor_util = data[:, 3]

    avg_sm_util = []
    avg_dram_util = []
    avg_tensor_util = []

    for i in range(len(times)):
        part_times = times[:i+1]
        frac_times = part_times / part_times.sum()

        avg_sm_util.append(np.average(sm_util[:i+1], weights=frac_times))
        avg_dram_util.append(np.average(dram_util[:i+1], weights=frac_times))
        avg_tensor_util.append(np.average(tensor_util[:i+1], weights=frac_times))

    xs = np.cumsum(times) / times.sum()
    # print(axs)
    axs[r, c].set_title(f'{prettyname}', fontsize=8)
    o1 = axs[r, c].plot(xs, sm_util, label='SM Utilization', linewidth=1)
    o2 = axs[r, c].plot(xs, avg_dram_util, label='Avg. DRAM Utilization', linewidth=1, linestyle='--')
    o3 = axs[r, c].plot(xs, avg_tensor_util, label='Avg. Tensor Utilization', linewidth=1, linestyle='--')

    axs[r, c].tick_params(axis='both', labelsize=6)
    axs[r, c].set_xlim([0, 1])
    # axs[r, c].set_yticklabels(fontsize=8)

    # axs[r, c].set_ylim([0, 100])
    # axs[r, c].semilogy()

    if c == 3:
        axs[r, c+1].set_title(f'{prettyname} (Chrono.)', fontsize=8)

        chrono_sm_util = chrono_data[:, 1]
        chrono_dram_util = chrono_data[:, 2]
        chrono_tensor_util = chrono_data[:, 3]

        axs[r, c+1].plot(xs, chrono_sm_util, label='SM Utilization', linewidth=0.2)
        axs[r, c+1].plot(xs, chrono_dram_util, label='Avg. DRAM Utilization', linewidth=0.2)
        axs[r, c+1].plot(xs, chrono_tensor_util, label='Avg. Tensor Utilization', linewidth=0.2)
        axs[r, c+1].tick_params(axis='both', labelsize=6)
        axs[r, c+1].set_xlim([0.5, 0.6])
        axs[r, c+1].set_xticks([0.5, 0.55, 0.6])


ax = fig.add_subplot(111, frameon=False)
if ORDER == 'sm_util': ax.set_xlabel('Fraction of Time', fontsize=8, labelpad=15)
else: ax.set_xlabel('Time', fontsize=8, labelpad=15)

ax.set_xticks([])
ax.set_yticks([])

plt.tight_layout()

plt.figlegend(
    [o1[0], o2[0], o3[0]],
    ['SM Utilization', 'DRAM Utilization', 'Tensor Utilization'],
    loc='lower center',
    ncol=3,
    fontsize=8,
    frameon=False)


os.makedirs('charts', exist_ok=True)
plt.subplots_adjust(wspace=0.3, hspace=0.5, bottom=0.20)
plt.savefig('charts/flame-chrono.pdf')



