#!/usr/bin/env python
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform
from matplotlib.patches import Rectangle

import numpy as np
import scipy
import utils
import utils.cache
import bins


colors = plt.rcParams['axes.prop_cycle'].by_key()['color']

colors = colors * 2

print(f'# colors = {len(colors)}')

plat = sys.argv[1]

fig = plt.figure(figsize=(utils.COL_WIDTH, 3.5))
ax0, ax1 = fig.subplots(2, 1, sharex='col')

labels0 = []
labels1 = []

def avg_runlen(kstats):
    run_lengths = []
    cur_bin = None
    for i in range(len(kstats)):
        this_bin = bins.get_bin_str_vec(kstats[i])

        if this_bin == cur_bin:
            run_lengths[-1] += 1
        else:
            run_lengths.append(1)
            cur_bin = this_bin

    return np.mean(run_lengths)

@utils.cache.cache_pickle
def get_runlens(plat, app):
    batch = utils.get_large_batch_size(plat, app)
    raw_file = utils.get_ncu_raw_file(plat, app, batch)

    if not os.path.exists(raw_file):
        print(f' {raw_file} does not exist')
        return []

    names, data = utils.read_ncu_raw_file_numpy(
        raw_file,
        [
            'gpu__time_duration.sum',
            'launch__thread_count',
            'sm__throughput.avg.pct_of_peak_sustained_elapsed',
            'gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed',
        ])

    ktimes = data[:, 0]
    tt = ktimes.sum()
    kstats = data[:, 1:4]

    run_lengths = []
    run_bins = []
    cur_bin = None

    is_gemm = []
    gemm_lengths = []
    cur_gemm = None

    avg_runlength = avg_runlen(kstats)

    for ki in range(len(names)):
        this_bin = bins.get_bin_str_vec(kstats[ki])

        if this_bin == cur_bin:
            run_lengths[-1] += ktimes[ki] / tt
        else:
            run_lengths.append(ktimes[ki] / tt)
            run_bins.append(this_bin)
            cur_bin = this_bin

        if utils.is_gemm(names[ki]) == cur_gemm:
            gemm_lengths[-1] += ktimes[ki] / tt
        else:
            gemm_lengths.append(ktimes[ki] / tt)
            is_gemm.append(utils.is_gemm(names[ki]))
            cur_gemm = utils.is_gemm(names[ki])

    return avg_runlength, np.array(run_lengths), np.array(run_bins), np.array(gemm_lengths), np.array(is_gemm)

for i, app in enumerate(utils.apps):
    batch = utils.get_large_batch_size(plat, app)
    raw_file = utils.get_ncu_raw_file(plat, app, batch)
    prettyname = utils.app_pretty_names[app]

    avg, runlens, runbins, gemmlens, isgemm = get_runlens(plat, app)

    labels0.append(f'{prettyname} ({avg:.1f})')
    labels1.append(f'{prettyname}')

    ti = 0
    for bin, rl in zip(runbins, runlens):
        bin_idx = bins.bin_str_to_idx[bin]
        ax0.add_patch(Rectangle((ti, i*4), rl, 3, lw=1, facecolor=bins.colors[bin_idx]))
        # if bin is large enough, add bin label as text

        ti += rl

    ti = 0
    for gemm, rl in zip(isgemm, gemmlens):
        if gemm: ax0.add_patch(Rectangle((ti, i*4), rl, 0.5, lw=1, facecolor='#000000'))
        ti += rl

    sorted_idxs = runbins.argsort()

    runlens = runlens[sorted_idxs]
    runbins = runbins[sorted_idxs]

    ti = 0

    gen = zip(runbins, runlens)

    cur_bin, cur_rl = next(gen)
    cur_bin_idx = bins.bin_str_to_idx[cur_bin]

    new_runbins = []
    new_runlens = []

    for bin, rl in gen:
        bin_idx = bins.bin_str_to_idx[bin]

        if bin_idx == cur_bin_idx:
            cur_rl += rl

        else:
            new_runbins.append(cur_bin)
            new_runlens.append(cur_rl)
            ti += cur_rl
            cur_bin = bin
            cur_bin_idx = bin_idx
            cur_rl = rl

    new_runbins.append(cur_bin)
    new_runlens.append(cur_rl)

    new_runbins = np.array(new_runbins)
    new_runlens = np.array(new_runlens)

    idxs = new_runlens.argsort()[::-1]
    new_runbins = new_runbins[idxs]
    new_runlens = new_runlens[idxs]

    print(new_runlens.sum(), new_runbins, new_runlens)

    ti = 0
    for bin, rl in zip(new_runbins, new_runlens):
        bin_idx = bins.bin_str_to_idx[bin]
        print('    ', bin, rl, bin_idx)
        ax1.add_patch(Rectangle((ti, i*4), rl, 3, lw=1, facecolor=bins.colors[bin_idx]))
        if rl > 0.08:
            ax1.text(ti + rl / 2, i*4 + 1.25, bin, ha='center', va='center', fontsize=6)
        ti += rl




ax0.set_title('(a) Chronological Order', fontsize=8)
ax0.set_yticks(np.arange(0, len(utils.apps)) * 4 + 3/2, labels0, fontsize=6)
ax0.tick_params(axis='both', labelsize=6)

ax0.set_xlim(0, 1.0)
ax0.set_ylim(0, 4 * len(utils.apps) - 1)

ax1.set_title('(b) Grouped by State', fontsize=8)
ax1.set_xlabel('Fraction of Time', fontsize=6)
ax1.set_yticks(np.arange(0, len(utils.apps)) * 4 + 3/2, labels1, fontsize=6)
ax1.tick_params(axis='both', labelsize=6)

ax1.set_xlim(0, 1.0)
ax1.set_ylim(0, 4 * len(utils.apps) - 1)

plt.tight_layout(pad=0)
os.makedirs('charts', exist_ok=True)
plt.savefig('charts/app-snap.pdf')



