#!/usr/bin/env python
import matplotlib.pyplot as plt
import seaborn as sns
import os
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform

import numpy as np
import utils

apps = utils.apps #[:4]

def get_sass_heatmap(sass_file):
    kernels = utils.parse_ncu_sass(sass_file)
    opcodes = utils.ncu_sass_opcodes(kernels)
    opcode_map = {op: i for i, op in enumerate(opcodes)}

    all_data = np.array([
        k.to_feature_vector(opcode_map)
        for k in kernels
    ])

    packed_dists = pdist(all_data, 'cosine')
    return 1 - squareform(packed_dists)


def get_hw_heatmap(raw_file):
    _, data = utils.read_ncu_raw_file_numpy(raw_file, utils.stats_of_interest[1:])
    packed_dists = pdist(data, 'cosine')
    return 1 - squareform(packed_dists)

fig = plt.figure(figsize=(6.5, 4))
axs = fig.subplots(4, len(apps) // 2)

for i, app in enumerate(apps):
    batch = utils.get_large_batch_size('a100', app)
    sass_file = utils.get_ncu_sass_file('a100', app, batch)
    raw_file = utils.get_ncu_raw_file('a100', app, batch)
    r, c = int((i % 2) * 2), int(i / 2)

    print(f'Processing {app}...')
    sass_heatmap = get_sass_heatmap(sass_file)
    hw_heatmap = get_hw_heatmap(raw_file)

    prettyname = utils.app_pretty_names[app]
    axs[r, c].set_title(f'{prettyname}')

    axs[r + 0, c].imshow(sass_heatmap, cmap='hot', interpolation='nearest')
    axs[r + 0, c].set_xlim(0, sass_heatmap.shape[1])
    axs[r + 0, c].set_ylim(0, sass_heatmap.shape[0])
    axs[r + 0, c].set_xticks([])
    axs[r + 0, c].set_yticks([])

    axs[r + 1, c].imshow(hw_heatmap, cmap='hot', interpolation='nearest')
    axs[r + 1, c].set_xlim(0, hw_heatmap.shape[1])
    axs[r + 1, c].set_ylim(0, hw_heatmap.shape[0])
    axs[r + 1, c].set_xticks([])
    axs[r + 1, c].set_yticks([])

    if c == 0:
        axs[r + 0, c].set_ylabel('SASS')
        axs[r + 1, c].set_ylabel('HW')


plt.tight_layout()

os.makedirs('charts', exist_ok=True)
plt.savefig('charts/similarities.pdf')



