#!/usr/bin/env python

import utils
import tfprof
import torchprof
import sys
import glob

plat = sys.argv[1]
app = sys.argv[2]
batch = int(sys.argv[3])


prof_file = None
for filename in glob.glob(f'{utils.CASIO}/casio-results/{plat}/{app}/*b{batch}-*'):
    if 'prof' in filename and filename.endswith('.txt'):
        prof_file = filename
        break
    elif 'trace' in filename and filename.endswith('.json'):
        prof_file = filename
        break

print(f'Found profile file: {prof_file}', file=sys.stderr)

trace : list[utils.FrameworkOp]

if prof_file.endswith('txt'):
    trace = tfprof.parse_tf_prof(prof_file)
elif prof_file.endswith('json'):
    trace = torchprof.parse_torch_prof(prof_file)

op : utils.FrameworkOp
for op in trace:
    print(f'{op.name}, {op.accel_time}')
