#!/usr/bin/env python
import sys
import utils

plat = sys.argv[1]
query_app = sys.argv[2]

batch_sizes = {}

with open(f'{utils.CASIO}/casio-results/summaries/{plat}-large-batch-list') as f:
    for line in f:
        [plat, app, batchstr] = line.strip().split('/')
        batch = int(batchstr.split('-')[-1])
        batch_sizes[app] = batch


print(f'{batch_sizes[query_app]}')
